import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Vazirmatn } from "next/font/google";
import localFont from "next/font/local";


const iranYekan= localFont({
  src: [
    {
      path: "../public/fonts/iranyekanwebmedium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/iranyekanwebregular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/YekanBakhBold.woff",
      weight: "700",
      style: "normal",
    },
  ],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa" dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body   className={`${iranYekan.className} min-h-full flex flex-col`}>
      
        {children}
        </body>
    </html>
  );
}
